name: aisleiq
version: "1.0.0"
config-version: 2
profile: aisleiq

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets: ["target", "dbt_packages"]

seeds:
  aisleiq:
    +schema: seeds

models:
  aisleiq:
    staging:
      +schema: staging
      +materialized: view
      stg_execucao_pdv:
        +materialized: table
      stg_execucao_pdv_dedup:
        +materialized: incremental
        +incremental_strategy: microbatch
        +event_time: source_date
        +begin: "2026-01-01"
        +batch_size: day
        +lookback: 2
    marts:
      +schema: marts
      +materialized: table
