-- AisleIQ: Snowflake provisioning (idempotent, safe to run again).
-- The wizard (scripts/setup_snowflake.sh) substitutes the public-key and
-- credit-cap placeholders and writes the final version outside the repo.
-- Run as ACCOUNTADMIN.

-- 1. Resource monitor (monthly cap for the project) --------------------------
-- OR REPLACE resets the tracked usage when re-run; the ALTER WAREHOUSE in
-- step 3 reattaches the monitor to the warehouse.
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE RESOURCE MONITOR AISLEIQ_RM
  WITH CREDIT_QUOTA = __CREDIT_QUOTA__
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND
           ON 110 PERCENT DO SUSPEND_IMMEDIATE;

-- 2. Roles (least privilege: one loads, the other transforms) ----------------
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS AISLEIQ_LOADER;
CREATE ROLE IF NOT EXISTS AISLEIQ_TRANSFORMER;
GRANT ROLE AISLEIQ_LOADER TO ROLE SYSADMIN;
GRANT ROLE AISLEIQ_TRANSFORMER TO ROLE SYSADMIN;

-- 3. X-Small warehouse, suspends after 60s idle -------------------------------
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS AISLEIQ_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  ENABLE_QUERY_ACCELERATION = FALSE
  GENERATION = '1'
  COMMENT = 'AisleIQ: load and transform';
-- Gen1 consumes 1.00 credit/h on X-Small; Gen2 consumes 1.35 (consumption
-- table of 2025-05-13). With ~22 MB of data, the 60s minimum per resume
-- dominates the cost, so Gen2's speed does not pay off. The ALTER covers the
-- case where the warehouse already existed as Gen2.
ALTER WAREHOUSE AISLEIQ_WH SET GENERATION = '1';
GRANT USAGE ON WAREHOUSE AISLEIQ_WH TO ROLE AISLEIQ_LOADER;
GRANT USAGE ON WAREHOUSE AISLEIQ_WH TO ROLE AISLEIQ_TRANSFORMER;
USE ROLE ACCOUNTADMIN;
ALTER WAREHOUSE AISLEIQ_WH SET RESOURCE_MONITOR = AISLEIQ_RM;

-- 4. Dev and prod databases, each with RAW / STAGING / MARTS ------------------
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS AISLEIQ_DEV;
CREATE DATABASE IF NOT EXISTS AISLEIQ_PROD;
CREATE SCHEMA IF NOT EXISTS AISLEIQ_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS AISLEIQ_DEV.STAGING;
CREATE SCHEMA IF NOT EXISTS AISLEIQ_DEV.MARTS;
CREATE SCHEMA IF NOT EXISTS AISLEIQ_PROD.RAW;
CREATE SCHEMA IF NOT EXISTS AISLEIQ_PROD.STAGING;
CREATE SCHEMA IF NOT EXISTS AISLEIQ_PROD.MARTS;

-- 5. Grants: loader writes to RAW; transformer reads RAW and writes to STAGING/MARTS
GRANT USAGE ON DATABASE AISLEIQ_DEV TO ROLE AISLEIQ_LOADER;
GRANT USAGE ON DATABASE AISLEIQ_DEV TO ROLE AISLEIQ_TRANSFORMER;
GRANT USAGE ON DATABASE AISLEIQ_PROD TO ROLE AISLEIQ_LOADER;
GRANT USAGE ON DATABASE AISLEIQ_PROD TO ROLE AISLEIQ_TRANSFORMER;

GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA AISLEIQ_DEV.RAW TO ROLE AISLEIQ_LOADER;
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA AISLEIQ_PROD.RAW TO ROLE AISLEIQ_LOADER;

GRANT USAGE ON SCHEMA AISLEIQ_DEV.RAW TO ROLE AISLEIQ_TRANSFORMER;
GRANT USAGE ON SCHEMA AISLEIQ_PROD.RAW TO ROLE AISLEIQ_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA AISLEIQ_DEV.RAW TO ROLE AISLEIQ_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AISLEIQ_DEV.RAW TO ROLE AISLEIQ_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA AISLEIQ_PROD.RAW TO ROLE AISLEIQ_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AISLEIQ_PROD.RAW TO ROLE AISLEIQ_TRANSFORMER;

GRANT ALL PRIVILEGES ON SCHEMA AISLEIQ_DEV.STAGING TO ROLE AISLEIQ_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA AISLEIQ_DEV.MARTS TO ROLE AISLEIQ_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA AISLEIQ_PROD.STAGING TO ROLE AISLEIQ_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA AISLEIQ_PROD.MARTS TO ROLE AISLEIQ_TRANSFORMER;

-- 6. Internal stage and file format in each RAW (created by the loader) -------
USE ROLE AISLEIQ_LOADER;
CREATE FILE FORMAT IF NOT EXISTS AISLEIQ_DEV.RAW.PARQUET_FMT TYPE = PARQUET;
CREATE STAGE IF NOT EXISTS AISLEIQ_DEV.RAW.LANDING FILE_FORMAT = AISLEIQ_DEV.RAW.PARQUET_FMT;
CREATE FILE FORMAT IF NOT EXISTS AISLEIQ_PROD.RAW.PARQUET_FMT TYPE = PARQUET;
CREATE STAGE IF NOT EXISTS AISLEIQ_PROD.RAW.LANDING FILE_FORMAT = AISLEIQ_PROD.RAW.PARQUET_FMT;

-- 7. Service user with key pair, no password ----------------------------------
USE ROLE SECURITYADMIN;
CREATE USER IF NOT EXISTS AISLEIQ_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = AISLEIQ_TRANSFORMER
  DEFAULT_WAREHOUSE = AISLEIQ_WH
  COMMENT = 'AisleIQ: service user (dbt and ingestion)';
ALTER USER AISLEIQ_SVC SET RSA_PUBLIC_KEY = '__RSA_PUBLIC_KEY__';
GRANT ROLE AISLEIQ_TRANSFORMER TO USER AISLEIQ_SVC;
GRANT ROLE AISLEIQ_LOADER TO USER AISLEIQ_SVC;

-- 8. Verification -------------------------------------------------------------
USE ROLE ACCOUNTADMIN;
SHOW GRANTS TO USER AISLEIQ_SVC;
SHOW WAREHOUSES LIKE 'AISLEIQ_WH';
SHOW RESOURCE MONITORS LIKE 'AISLEIQ_RM';
