#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Folders outside the repo: private key, .env and the final SQL with the public key.
CONN_DIR="${CONN_DIR:-$HOME/.aisleiq}"
ENV_FILE="${AISLEIQ_ENV_FILE:-$CONN_DIR/aisleiq.env}"
KEY_FILE="$CONN_DIR/aisleiq_rsa_key.p8"
PUB_FILE="$CONN_DIR/aisleiq_rsa_key.pub"
SQL_OUT="$CONN_DIR/aisleiq_provision.sql"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
mkdir -p "$CONN_DIR"

_win() { command -v cygpath >/dev/null 2>&1 && cygpath -m "$1" || printf '%s' "$1"; }

banner "AisleIQ: provision Snowflake"

# ── 1. Account and credit cap ─────────────────────────────────────────────
stage "Snowflake account and credit cap"
say "We need the account identifier and the project's credit cap."
open_url "https://app.snowflake.com"
step "Snowsight → click your name (bottom left) → Account → View account details."
step "Copy the 'Account identifier' in the ORGNAME-ACCOUNTNAME format (e.g. MYORG-MYACCOUNT)."
ask SNOWFLAKE_ACCOUNT "Account identifier:"
[[ "$SNOWFLAKE_ACCOUNT" == *-* ]] || { warn "expected ORGNAME-ACCOUNTNAME (with a hyphen)"; exit 1; }
open_url "https://app.snowflake.com"
step "Admin → Billing: check the trial balance and the credit price."
note "Suggested cap for this project: 20 credits."
ask CREDIT_QUOTA "Credit cap for AISLEIQ_RM (Enter = 20):"
CREDIT_QUOTA="${CREDIT_QUOTA:-20}"
[[ "$CREDIT_QUOTA" =~ ^[0-9]+$ ]] || { warn "the cap must be an integer"; exit 1; }
write_env SNOWFLAKE_ACCOUNT "$SNOWFLAKE_ACCOUNT"
write_env CREDIT_QUOTA "$CREDIT_QUOTA"

# ── 2. Key pair ───────────────────────────────────────────────────────────
stage "RSA key pair (passwordless authentication)"
say "The private key stays in $CONN_DIR, never inside the repo."
if [[ -f "$KEY_FILE" ]]; then
  note "$KEY_FILE already exists; reusing it. (Delete it and re-run to rotate.)"
else
  openssl genrsa 2048 2>/dev/null | openssl pkcs8 -topk8 -inform PEM -nocrypt -out "$KEY_FILE"
  openssl rsa -in "$KEY_FILE" -pubout -out "$PUB_FILE" 2>/dev/null
  printf '  %s✓ generated%s %s\n' "$GREEN" "$RESET" "$KEY_FILE"
fi
[[ -f "$PUB_FILE" ]] || openssl rsa -in "$KEY_FILE" -pubout -out "$PUB_FILE" 2>/dev/null
warn "The private key has no passphrase: protect the $CONN_DIR folder."

# ── 3. Provisioning SQL ───────────────────────────────────────────────────
stage "Generate the provisioning SQL"
PUBKEY_BODY=$(grep -v -- '-----' "$PUB_FILE" | tr -d '\n\r')
sed -e "s|__RSA_PUBLIC_KEY__|$PUBKEY_BODY|g" -e "s|__CREDIT_QUOTA__|$CREDIT_QUOTA|g" \
  "$REPO_ROOT/infra/provision.sql" > "$SQL_OUT"
say "SQL written to: $SQL_OUT"
say "It creates: AISLEIQ_RM monitor, roles, AISLEIQ_WH warehouse, DEV/PROD databases,"
say "RAW/STAGING/MARTS schemas, internal stages and the AISLEIQ_SVC user."
if command -v clip.exe >/dev/null 2>&1; then
  clip.exe < "$SQL_OUT" && note "The contents were also copied to the clipboard."
fi

# ── 4. Run in Snowsight ───────────────────────────────────────────────────
stage "Run the SQL in Snowsight as ACCOUNTADMIN"
open_url "https://app.snowflake.com"
step "Projects → Worksheets → '+' → SQL Worksheet."
step "Paste the contents (Ctrl+V, or open $SQL_OUT) and use 'Run all' (arrow next to Run)."
step "The starting role can be anything: the script switches roles itself. Your user needs ACCOUNTADMIN."
step "At the end, the 3 SHOW statements should list AISLEIQ_SVC with 2 roles, AISLEIQ_WH and AISLEIQ_RM."
warn "Without a verified email on your user, the 75% NOTIFY will not arrive (Snowsight → Profile)."
confirm "Did the script run without errors?" || { warn "Fix the errors and re-run the wizard."; exit 1; }

# ── 5. Variables, dbt profile and connection test ─────────────────────────
stage "Connect dbt and test"
write_env SNOWFLAKE_USER "AISLEIQ_SVC"
write_env SNOWFLAKE_PRIVATE_KEY_PATH "$(_win "$KEY_FILE")"
write_env SNOWFLAKE_ROLE "AISLEIQ_TRANSFORMER"
write_env SNOWFLAKE_WAREHOUSE "AISLEIQ_WH"
write_env SNOWFLAKE_DATABASE "AISLEIQ_DEV"
[[ -f "$REPO_ROOT/dbt/profiles.yml" ]] || cp "$REPO_ROOT/dbt/profiles.yml.example" "$REPO_ROOT/dbt/profiles.yml"
DBT_BIN="$REPO_ROOT/.venv/Scripts/dbt.exe"; [[ -x "$DBT_BIN" ]] || DBT_BIN="$REPO_ROOT/.venv/bin/dbt"
if [[ -x "$DBT_BIN" ]] && confirm "Run 'dbt debug' now? (wakes the warehouse for ~1 min)"; then
  set -a
  # shellcheck source=/dev/null
  source "$ENV_FILE"
  set +a
  ( cd "$REPO_ROOT/dbt" && DBT_PROFILES_DIR="$REPO_ROOT/dbt" "$DBT_BIN" debug ) \
    || SKIPPED+=("dbt debug failed: check the env file and the public key on the AISLEIQ_SVC user")
else
  SKIPPED+=("run 'dbt debug' inside dbt/ (see docs/setup.md)")
fi

finish
